[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --reuse-db -p no:cacheprovider -p no:celery --tb=short
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning
