# Generated by Django 5.2.11 on 2026-02-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='channels_app.telegramchannel'),
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['placement', 'event_type'], name='ad_events_placeme_fcc00b_idx'),
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['created_at'], name='ad_events_created_844aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystats',
            index=models.Index(fields=['date'], name='daily_stats_date_c5e813_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailystats',
            unique_together={('date', 'campaign', 'channel')},
        ),
    ]
