# Generated by Django 5.2.11 on 2026-04-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_daily_funnel_stats'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clickevent',
            new_name='click_event_placeme_d0eb1a_idx',
            old_name='click_event_place_sus_idx',
        ),
        migrations.RenameIndex(
            model_name='clickevent',
            new_name='click_event_created_d7ad0c_idx',
            old_name='click_event_created_idx',
        ),
        migrations.RenameIndex(
            model_name='clickevent',
            new_name='click_event_ip_subn_35f1ca_idx',
            old_name='click_event_subnet_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyfunnelstats',
            new_name='daily_funne_campaig_ada5da_idx',
            old_name='funnel_camp_date_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyfunnelstats',
            new_name='daily_funne_ad_id_ee9cfe_idx',
            old_name='funnel_ad_date_idx',
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailyfunnelstats',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
