# Generated by Django 5.2.11 on 2026-04-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversion',
            new_name='conversions_campaig_eb6678_idx',
            old_name='conv_camp_date_idx',
        ),
        migrations.RenameIndex(
            model_name='conversion',
            new_name='conversions_placeme_633ede_idx',
            old_name='conv_place_date_idx',
        ),
        migrations.RenameIndex(
            model_name='conversion',
            new_name='conversions_click_e_56e418_idx',
            old_name='conv_click_idx',
        ),
        migrations.RenameIndex(
            model_name='conversionevent',
            new_name='conversion__pixel_i_f3207e_idx',
            old_name='conv_ev_pix_name_date_idx',
        ),
        migrations.RenameIndex(
            model_name='conversionevent',
            new_name='conversion__attribu_4b12e1_idx',
            old_name='conv_ev_attr_attempt_idx',
        ),
        migrations.AlterField(
            model_name='conversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conversionevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pixelinstallation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
