# Generated by Django 5.2.11 on 2026-02-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='📁', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('mixed', 'Aralash')], default='uz', max_length=5)),
                ('subscriber_count', models.IntegerField(default=0)),
                ('avg_views', models.IntegerField(default=0, help_text='Ortalama post görüntülenmesi')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('suspended', 'Askıya Alındı')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('bot_added', models.BooleanField(default=False, help_text='Bot kanala admin olarak eklendi mi?')),
                ('max_ads_per_day', models.IntegerField(default=3)),
                ('min_cpm', models.DecimalField(decimal_places=2, default=5000, help_text='Minimum CPM (UZS cinsinden)', max_digits=10)),
                ('ad_hours_start', models.IntegerField(default=9, help_text='Reklam başlangıç saati')),
                ('ad_hours_end', models.IntegerField(default=22, help_text='Reklam bitiş saati')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='channels_app.category')),
            ],
            options={
                'db_table': 'telegram_channels',
                'ordering': ['-subscriber_count'],
            },
        ),
    ]
