# Generated by Django 5.2.11 on 2026-04-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0004_daily_channel_snapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailychannelsnapshot',
            new_name='daily_chann_channel_613625_idx',
            old_name='daily_chan_channel_date_idx',
        ),
        migrations.RenameIndex(
            model_name='dailychannelsnapshot',
            new_name='daily_chann_suspici_6f7785_idx',
            old_name='daily_chan_susp_growth_idx',
        ),
        migrations.AlterField(
            model_name='dailychannelsnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
