# Generated by Django 5.2.11 on 2026-04-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_backfill_balances'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payment_aud_provide_d48201_idx',
            old_name='audit_prov_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentauditlog',
            new_name='payment_aud_event_t_107e0e_idx',
            old_name='audit_event_created_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payment_tra_user_id_001d5d_idx',
            old_name='tx_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payment_tra_type_f892dc_idx',
            old_name='tx_type_status_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='payment_tra_provide_fd53cf_idx',
            old_name='tx_provider_ref_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentauditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
