# Generated by Django 5.2.11 on 2026-02-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('text', 'Sadece Metin'), ('image', 'Görsel + Metin'), ('video', 'Video + Metin')], default='text', max_length=10)),
                ('text_uz', models.TextField(help_text='Reklam metni (Özbekçe)')),
                ('text_ru', models.TextField(blank=True, default='', help_text='Reklam metni (Rusça)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='ads/videos/')),
                ('button_text', models.CharField(blank=True, default='', max_length=50)),
                ('button_url', models.URLField(blank=True, default='')),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ads',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('pending', 'Onay Bekliyor'), ('active', 'Aktif'), ('paused', 'Duraklatıldı'), ('completed', 'Tamamlandı'), ('rejected', 'Reddedildi')], default='draft', max_length=20)),
                ('target_languages', models.JSONField(default=list, help_text='Hedef diller, örn: ["uz", "ru"]')),
                ('min_subscribers', models.IntegerField(default=0)),
                ('billing_type', models.CharField(choices=[('cpm', 'CPM (1000 Gösterim)'), ('cpc', 'CPC (Tıklama Başı)')], default='cpm', max_length=10)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bid_amount', models.DecimalField(decimal_places=2, help_text='CPM veya CPC teklif tutarı (UZS)', max_digits=10)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Planlandı'), ('sent', 'Gönderildi'), ('failed', 'Başarısız'), ('deleted', 'Silindi')], default='scheduled', max_length=20)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('publisher_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delete_after_hours', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='ads.ad')),
            ],
            options={
                'db_table': 'ad_placements',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
