# Generated by Django 5.2.11 on 2026-02-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adplacement',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_placements', to='channels_app.telegramchannel'),
        ),
    ]
