# Generated by Django 5.2.11 on 2026-02-15 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0002_initial'),
        ('channels_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_categories',
            field=models.ManyToManyField(blank=True, related_name='targeted_campaigns', to='channels_app.category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='adplacement',
            unique_together={('ad', 'channel', 'scheduled_at')},
        ),
    ]
