# Generated by Django 5.2.11 on 2026-02-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('pending', 'Onay Bekliyor'), ('active', 'Aktif'), ('paused', 'Duraklatıldı'), ('completed', 'Tamamlandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20),
        ),
    ]
