# Generated by Django 5.2.11 on 2026-02-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_campaign_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='video',
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('text', 'Sadece Metin'), ('image', 'Görsel + Metin')], default='text', max_length=10),
        ),
    ]
