# Generated by Django 5.2.11 on 2026-02-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Admin tarafından red edilme sebebi'),
        ),
    ]
