# Generated by Django 5.2.11 on 2026-02-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_campaign_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Boş bırakılırsa hemen başlar', null=True),
        ),
    ]
