# Generated by Django 5.2.11 on 2026-04-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_utm_and_ab_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advariantexperiment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
