# Generated by Django 5.2.11 on 2026-02-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_moderate_channels', 'Kanalları moderasyon yapabilir'), ('can_review_campaigns', 'Kampanya inceleyebilir'), ('can_manage_users', 'Kullanıcı yönetebilir'), ('can_view_revenue', 'Gelir raporlarını görebilir'), ('can_manage_categories', 'Kategorileri yönetebilir'), ('can_approve_payouts', 'Ödeme taleplerini onaylayabilir')]},
        ),
    ]
