# Generated by Django 5.2.11 on 2026-02-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_description',
            field=models.TextField(blank=True, default='', help_text='Şirket hakkında kısa açıklama'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Şirket web sitesi'),
        ),
    ]
